from models import Place

places_db = [
    Place(id=1, name="Bali", country="Indonesia", category="Beach", region="Asia",
          description="A tropical paradise known for its stunning beaches, rice terraces, and vibrant nightlife.",
          image_url="https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600",
          rating=4.8, best_season="April - October", entry_fee="Free"),
    Place(id=2, name="Santorini", country="Greece", category="City", region="Europe",
          description="Famous for its white-washed buildings, blue domes, and breathtaking sunsets over the Aegean Sea.",
          image_url="https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=600",
          rating=4.9, best_season="June - September", entry_fee="Free"),
    Place(id=3, name="Machu Picchu", country="Peru", category="Heritage", region="Americas",
          description="An ancient Inca citadel set high in the Andes Mountains, a UNESCO World Heritage Site.",
          image_url="https://images.unsplash.com/photo-1526392060635-9d6019884377?w=600",
          rating=4.9, best_season="May - October", entry_fee="$45"),
    Place(id=4, name="Serengeti", country="Tanzania", category="Nature", region="Africa",
          description="Home to the world's greatest wildlife spectacle -- the Great Migration of over 1.5 million wildebeest.",
          image_url="https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600",
          rating=4.8, best_season="June - October", entry_fee="$60/day"),
    Place(id=5, name="Mount Everest Base Camp", country="Nepal", category="Adventure", region="Asia",
          description="Trek to the base of the world's highest mountain through stunning Himalayan landscapes.",
          image_url="https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600",
          rating=4.7, best_season="March - May", entry_fee="$11"),
    Place(id=6, name="Great Barrier Reef", country="Australia", category="Nature", region="Oceania",
          description="The world's largest coral reef system, home to thousands of marine species.",
          image_url="https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=600",
          rating=4.8, best_season="June - October", entry_fee="Free"),
    Place(id=7, name="Petra", country="Jordan", category="Heritage", region="Middle East",
          description="An ancient city carved into rose-red cliffs, known as the 'Rose City'.",
          image_url="https://images.unsplash.com/photo-1548786811-dd6e453ccca7?w=600",
          rating=4.8, best_season="March - May", entry_fee="$70"),
    Place(id=8, name="Banff National Park", country="Canada", category="Mountain", region="Americas",
          description="Stunning turquoise lakes, glaciers, and rugged mountain peaks in the Canadian Rockies.",
          image_url="https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600",
          rating=4.9, best_season="June - August", entry_fee="$10/day"),
    Place(id=9, name="Amalfi Coast", country="Italy", category="Beach", region="Europe",
          description="A dramatic stretch of coastline with cliffside villages, turquoise waters, and lemon groves.",
          image_url="https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?w=600",
          rating=4.7, best_season="May - September", entry_fee="Free"),
    Place(id=10, name="Tokyo", country="Japan", category="City", region="Asia",
          description="A dazzling mix of ultramodern and traditional culture, from neon-lit skyscrapers to historic temples.",
          image_url="https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600",
          rating=4.9, best_season="March - May", entry_fee="Free"),
    Place(id=11, name="Victoria Falls", country="Zimbabwe", category="Adventure", region="Africa",
          description="One of the world's largest waterfalls, known locally as 'The Smoke That Thunders'.",
          image_url="https://images.unsplash.com/photo-1544979377-3851d1e1f3e6?w=600",
          rating=4.8, best_season="February - May", entry_fee="$30"),
    Place(id=12, name="Patagonia", country="Argentina", category="Mountain", region="Americas",
          description="Remote wilderness at the southern tip of South America with dramatic peaks and glaciers.",
          image_url="https://images.unsplash.com/photo-1531761535209-180857e963b9?w=600",
          rating=4.7, best_season="November - March", entry_fee="Free"),
    Place(id=13, name="Dubrovnik", country="Croatia", category="City", region="Europe",
          description="Known as the 'Pearl of the Adriatic', with medieval walls and crystal-clear waters.",
          image_url="https://images.unsplash.com/photo-1555990793-da11153b6745?w=600",
          rating=4.7, best_season="May - September", entry_fee="Free"),
    Place(id=14, name="Maldives", country="Maldives", category="Beach", region="Asia",
          description="Pristine white-sand beaches, overwater bungalows, and crystal-clear turquoise lagoons.",
          image_url="https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=600",
          rating=4.9, best_season="November - April", entry_fee="Free"),
    Place(id=15, name="Cappadocia", country="Turkey", category="Adventure", region="Middle East",
          description="Famous for its unique fairy chimneys, cave hotels, and magical hot air balloon rides.",
          image_url="https://images.unsplash.com/photo-1570939274717-7eda259b50ed?w=600",
          rating=4.8, best_season="April - June", entry_fee="Free"),
    Place(id=16, name="Angkor Wat", country="Cambodia", category="Heritage", region="Asia",
          description="The largest religious monument in the world, a symbol of Cambodia's rich Khmer heritage.",
          image_url="https://images.unsplash.com/photo-1508159452718-d22f6734a236?w=600",
          rating=4.8, best_season="November - March", entry_fee="$37"),
    Place(id=17, name="Fjords of Norway", country="Norway", category="Nature", region="Europe",
          description="Dramatic landscapes of deep blue fjords, towering cliffs, and cascading waterfalls.",
          image_url="https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=600",
          rating=4.9, best_season="June - August", entry_fee="Free"),
    Place(id=18, name="Sahara Desert", country="Morocco", category="Adventure", region="Africa",
          description="The world's largest hot desert offering camel treks, star-gazing, and golden sand dunes.",
          image_url="https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=600",
          rating=4.6, best_season="October - April", entry_fee="Free"),
    Place(id=19, name="Kyoto", country="Japan", category="Heritage", region="Asia",
          description="Japan's ancient capital with over 1,600 Buddhist temples, Shinto shrines, and traditional tea houses.",
          image_url="https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600",
          rating=4.9, best_season="March - May", entry_fee="Free"),
    Place(id=20, name="Queenstown", country="New Zealand", category="Adventure", region="Oceania",
          description="The adventure capital of the world, offering bungee jumping, skydiving, and skiing.",
          image_url="https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=600",
          rating=4.8, best_season="December - February", entry_fee="Free"),
    Place(id=21, name="Phuket", country="Thailand", category="Beach", region="Asia",
          description="Thailand's largest island with white-sand beaches, clear waters, and vibrant street food.",
          image_url="https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=600",
          rating=4.6, best_season="November - April", entry_fee="Free"),
    Place(id=22, name="Swiss Alps", country="Switzerland", category="Mountain", region="Europe",
          description="World-class skiing, scenic train rides, and charming alpine villages.",
          image_url="https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600",
          rating=4.9, best_season="December - March", entry_fee="Free"),
          Place(id=23, name="Taj Mahal", country="India", category="Heritage", region="Asia",
          description="One of the world's most iconic monuments, a stunning white marble mausoleum built by Mughal Emperor Shah Jahan.",
          image_url="https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600",
          rating=4.9, best_season="October - March", entry_fee="$15"),
    Place(id=24, name="Kerala Backwaters", country="India", category="Nature", region="Asia",
          description="A serene network of lagoons, lakes, and canals lined with palm trees and traditional houseboats.",
          image_url="https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600",
          rating=4.7, best_season="September - March", entry_fee="Free"),
    Place(id=25, name="Hunza Valley", country="Pakistan", category="Mountain", region="Asia",
          description="A breathtaking valley surrounded by some of the world's highest peaks including Rakaposhi and Ultar Sar.",
          image_url="https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=600",
          rating=4.8, best_season="April - October", entry_fee="Free"),
    Place(id=26, name="Tiger's Nest Monastery", country="Bhutan", category="Heritage", region="Asia",
          description="A sacred Buddhist monastery perched dramatically on a cliff 3,000 feet above the Paro Valley.",
          image_url="https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
          rating=4.9, best_season="March - May", entry_fee="$200/day"),
    Place(id=27, name="Sigiriya Rock Fortress", country="Sri Lanka", category="Heritage", region="Asia",
          description="An ancient rock fortress rising 200 meters above the jungle, with stunning frescoes and royal gardens.",
          image_url="https://images.unsplash.com/photo-1546708770-599a3abdf230?w=600",
          rating=4.7, best_season="December - April", entry_fee="$30"),
    Place(id=28, name="Bagan Temples", country="Myanmar", category="Heritage", region="Asia",
          description="A plain dotted with over 2,000 ancient Buddhist temples and pagodas, best seen at sunrise by hot air balloon.",
          image_url="https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600",
          rating=4.8, best_season="November - February", entry_fee="$20"),
    Place(id=29, name="Sundarbans", country="Bangladesh", category="Nature", region="Asia",
          description="The world's largest mangrove forest, home to the Royal Bengal Tiger and diverse wildlife.",
          image_url="https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=600",
          rating=4.5, best_season="October - March", entry_fee="$10"),
    Place(id=30, name="Great Wall of China", country="China", category="Heritage", region="Asia",
          description="A series of fortifications stretching over 13,000 miles, one of the greatest architectural feats in history.",
          image_url="https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=600",
          rating=4.9, best_season="April - October", entry_fee="$10"),

]

next_id = 31